import type { CityNode, HighwaySegment } from './types';

// World map coordinates use a 1000x520 viewBox (equirectangular-ish projection)
// x: 0=180W -> 1000=180E, y: 0=90N -> 520=90S

export const CITIES: CityNode[] = [
  // ── North America ──
  { id: 'nyc', name: 'New York', state: 'USA', x: 290, y: 200, image: 'https://images.pexels.com/photos/802024/pexels-photo-802024.jpeg?auto=compress&cs=tinysrgb&w=800', description: 'The Big Apple — skyscrapers, Broadway, and the city that never sleeps.' },
  { id: 'losangeles', name: 'Los Angeles', state: 'USA', x: 170, y: 230, image: 'https://images.pexels.com/photos/2253977/pexels-photo-2253977.jpeg?auto=compress&cs=tinysrgb&w=800', description: 'City of Angels — Hollywood, beaches, and endless freeways.' },
  { id: 'chicago', name: 'Chicago', state: 'USA', x: 255, y: 190, image: 'https://images.pexels.com/photos/7804113/pexels-photo-7804113.jpeg?auto=compress&cs=tinysrgb&w=800', description: 'The Windy City — stunning lakefront and bold architecture.' },
  { id: 'miami', name: 'Miami', state: 'USA', x: 270, y: 250, image: 'https://images.pexels.com/photos/6449863/pexels-photo-6449863.jpeg?auto=compress&cs=tinysrgb&w=800', description: 'Tropical paradise with Art Deco architecture and vibrant nightlife.' },
  { id: 'toronto', name: 'Toronto', state: 'Canada', x: 275, y: 175, image: 'https://images.pexels.com/photos/209269/pexels-photo-209269.jpeg?auto=compress&cs=tinysrgb&w=800', description: 'Canada\'s largest city — CN Tower, multicultural neighborhoods, and Lake Ontario.' },
  { id: 'mexicocity', name: 'Mexico City', state: 'Mexico', x: 225, y: 260, image: 'https://images.pexels.com/photos/2086361/pexels-photo-2086361.jpeg?auto=compress&cs=tinysrgb&w=800', description: 'Vibrant capital with Aztec ruins, colonial architecture, and incredible food.' },
  { id: 'vancouver', name: 'Vancouver', state: 'Canada', x: 175, y: 160, image: 'https://images.pexels.com/photos/2287310/pexels-photo-2287310.jpeg?auto=compress&cs=tinysrgb&w=800', description: 'Pacific coast gem with mountains, ocean, and Stanley Park.' },

  // ── South America ──
  { id: 'rio', name: 'Rio de Janeiro', state: 'Brazil', x: 365, y: 370, image: 'https://images.pexels.com/photos/2086361/pexels-photo-2086361.jpeg?auto=compress&cs=tinysrgb&w=800', description: 'Christ the Redeemer, Copacabana Beach, and Carnival spirit.' },
  { id: 'saopaulo', name: 'São Paulo', state: 'Brazil', x: 360, y: 380, image: 'https://images.pexels.com/photos/2874168/pexels-photo-2874168.jpeg?auto=compress&cs=tinysrgb&w=800', description: 'South America\'s financial hub with world-class dining and culture.' },
  { id: 'buenosaires', name: 'Buenos Aires', state: 'Argentina', x: 325, y: 420, image: 'https://images.pexels.com/photos/2774779/pexels-photo-2774779.jpeg?auto=compress&cs=tinysrgb&w=800', description: 'Paris of South America — tango, steak, and European-style boulevards.' },
  { id: 'lima', name: 'Lima', state: 'Peru', x: 300, y: 350, image: 'https://images.pexels.com/photos/2037336/pexels-photo-2037336.jpeg?auto=compress&cs=tinysrgb&w=800', description: 'Pacific coast capital with pre-Columbian ruins and world-renowned cuisine.' },
  { id: 'bogota', name: 'Bogotá', state: 'Colombia', x: 295, y: 310, image: 'https://images.pexels.com/photos/3787839/pexels-photo-3787839.jpeg?auto=compress&cs=tinysrgb&w=800', description: 'High-altitude Andean capital with gold museums and cable car views.' },

  // ── Europe ──
  { id: 'london', name: 'London', state: 'UK', x: 495, y: 160, image: 'https://images.pexels.com/photos/672532/pexels-photo-672532.jpeg?auto=compress&cs=tinysrgb&w=800', description: 'Historic capital with Big Ben, Tower Bridge, and royal palaces.' },
  { id: 'paris', name: 'Paris', state: 'France', x: 505, y: 175, image: 'https://images.pexels.com/photos/161853/eiffel-tower-paris-france-tower-161853.jpeg?auto=compress&cs=tinysrgb&w=800', description: 'City of Light — Eiffel Tower, Louvre, and romantic boulevards.' },
  { id: 'rome', name: 'Rome', state: 'Italy', x: 525, y: 195, image: 'https://images.pexels.com/photos/2225442/pexels-photo-2225442.jpeg?auto=compress&cs=tinysrgb&w=800', description: 'The Eternal City — Colosseum, Vatican, and ancient ruins at every turn.' },
  { id: 'madrid', name: 'Madrid', state: 'Spain', x: 495, y: 195, image: 'https://images.pexels.com/photos/280219/pexels-photo-280219.jpeg?auto=compress&cs=tinysrgb&w=800', description: 'Spain\'s vibrant capital with grand plazas, tapas, and world-class art.' },
  { id: 'berlin', name: 'Berlin', state: 'Germany', x: 525, y: 160, image: 'https://images.pexels.com/photos/1878293/pexels-photo-1878293.jpeg?auto=compress&cs=tinysrgb&w=800', description: 'Germany\'s capital — Brandenburg Gate, Wall history, and edgy culture.' },
  { id: 'amsterdam', name: 'Amsterdam', state: 'Netherlands', x: 515, y: 155, image: 'https://images.pexels.com/photos/1796715/pexels-photo-1796715.jpeg?auto=compress&cs=tinysrgb&w=800', description: 'Canals, bicycles, and Golden Age architecture in this charming city.' },
  { id: 'barcelona', name: 'Barcelona', state: 'Spain', x: 500, y: 190, image: 'https://images.pexels.com/photos/819764/pexels-photo-819764.jpeg?auto=compress&cs=tinysrgb&w=800', description: 'Gaudí\'s masterpieces, Mediterranean beaches, and Gothic Quarter.' },
  { id: 'lisbon', name: 'Lisbon', state: 'Portugal', x: 480, y: 200, image: 'https://images.pexels.com/photos/1534560/pexels-photo-1534560.jpeg?auto=compress&cs=tinysrgb&w=800', description: 'Seven hills, yellow trams, and Atlantic charm.' },
  { id: 'vienna', name: 'Vienna', state: 'Austria', x: 535, y: 175, image: 'https://images.pexels.com/photos/1098377/pexels-photo-1098377.jpeg?auto=compress&cs=tinysrgb&w=800', description: 'Imperial palaces, coffee houses, and classical music heritage.' },
  { id: 'prague', name: 'Prague', state: 'Czech Republic', x: 535, y: 165, image: 'https://images.pexels.com/photos/2207564/pexels-photo-2207564.jpeg?auto=compress&cs=tinysrgb&w=800', description: 'Fairytale city with Charles Bridge, castle, and Old Town Square.' },
  { id: 'istanbul', name: 'Istanbul', state: 'Türkiye', x: 565, y: 185, image: 'https://images.pexels.com/photos/1549366/pexels-photo-1549366.jpeg?auto=compress&cs=tinysrgb&w=800', description: 'Where East meets West — Hagia Sophia, bazaars, and Bosphorus views.' },
  { id: 'athens', name: 'Athens', state: 'Greece', x: 555, y: 205, image: 'https://images.pexels.com/photos/5252364/pexels-photo-5252364.jpeg?auto=compress&cs=tinysrgb&w=800', description: 'Cradle of civilization — Acropolis, ancient agora, and Mediterranean sun.' },
  { id: 'moscow', name: 'Moscow', state: 'Russia', x: 580, y: 140, image: 'https://images.pexels.com/photos/7533393/pexels-photo-7533393.jpeg?auto=compress&cs=tinysrgb&w=800', description: 'Red Square, St. Basil\'s Cathedral, and the mighty Kremlin.' },
  { id: 'stockholm', name: 'Stockholm', state: 'Sweden', x: 535, y: 130, image: 'https://images.pexels.com/photos/1123116/pexels-photo-1123116.jpeg?auto=compress&cs=tinysrgb&w=800', description: 'Scandinavian capital spread across 14 islands with Gamla Stan charm.' },
  { id: 'oslo', name: 'Oslo', state: 'Norway', x: 525, y: 135, image: 'https://images.pexels.com/photos/1123116/pexels-photo-1123116.jpeg?auto=compress&cs=tinysrgb&w=800', description: 'Fjord-side capital with Viking history and modern architecture.' },

  // ── Asia ──
  { id: 'tokyo', name: 'Tokyo', state: 'Japan', x: 855, y: 195, image: 'https://images.pexels.com/photos/2506923/pexels-photo-2506923.jpeg?auto=compress&cs=tinysrgb&w=800', description: 'Neon-lit metropolis blending ancient temples with futuristic tech.' },
  { id: 'osaka', name: 'Osaka', state: 'Japan', x: 850, y: 205, image: 'https://images.pexels.com/photos/2506923/pexels-photo-2506923.jpeg?auto=compress&cs=tinysrgb&w=800', description: 'Japan\'s kitchen — street food, castle, and vibrant nightlife.' },
  { id: 'seoul', name: 'Seoul', state: 'South Korea', x: 835, y: 185, image: 'https://images.pexels.com/photos/2377833/pexels-photo-2377833.jpeg?auto=compress&cs=tinysrgb&w=800', description: 'K-pop, palaces, and cutting-edge technology in dynamic capital.' },
  { id: 'beijing', name: 'Beijing', state: 'China', x: 800, y: 175, image: 'https://images.pexels.com/photos/161901/paris-sunset-france-monument-161901.jpeg?auto=compress&cs=tinysrgb&w=800', description: 'Forbidden City, Great Wall, and China\'s ancient imperial capital.' },
  { id: 'shanghai', name: 'Shanghai', state: 'China', x: 820, y: 190, image: 'https://images.pexels.com/photos/1534560/pexels-photo-1534560.jpeg?auto=compress&cs=tinysrgb&w=800', description: 'Bund waterfront, soaring skyscrapers, and bustling Bund.' },
  { id: 'hongkong', name: 'Hong Kong', state: 'China', x: 820, y: 225, image: 'https://images.pexels.com/photos/887524/pexels-photo-887524.jpeg?auto=compress&cs=tinysrgb&w=800', description: 'Skyline, harbor, and East-meets-West energy.' },
  { id: 'bangkok', name: 'Bangkok', state: 'Thailand', x: 780, y: 235, image: 'https://images.pexels.com/photos/209778/pexels-photo-209778.jpeg?auto=compress&cs=tinysrgb&w=800', description: 'Golden temples, floating markets, and legendary street food.' },
  { id: 'singapore', name: 'Singapore', state: 'Singapore', x: 795, y: 270, image: 'https://images.pexels.com/photos/819764/pexels-photo-819764.jpeg?auto=compress&cs=tinysrgb&w=800', description: 'Garden city with Marina Bay, hawker centers, and tropical greenery.' },
  { id: 'mumbai', name: 'Mumbai', state: 'India', x: 720, y: 225, image: 'https://images.pexels.com/photos/3581368/pexels-photo-3581368.jpeg?auto=compress&cs=tinysrgb&w=800', description: 'Bollywood, Gateway of India, and maximum city energy.' },
  { id: 'delhi', name: 'Delhi', state: 'India', x: 735, y: 200, image: 'https://images.pexels.com/photos/3581368/pexels-photo-3581368.jpeg?auto=compress&cs=tinysrgb&w=800', description: 'Red Fort, India Gate, and centuries of Mughal history.' },
  { id: 'dubai', name: 'Dubai', state: 'UAE', x: 655, y: 215, image: 'https://images.pexels.com/photos/1470502/pexels-photo-1470502.jpeg?auto=compress&cs=tinysrgb&w=800', description: 'Burj Khalifa, luxury shopping, and desert adventures.' },
  { id: 'tehran', name: 'Tehran', state: 'Iran', x: 635, y: 190, image: 'https://images.pexels.com/photos/1534560/pexels-photo-1534560.jpeg?auto=compress&cs=tinysrgb&w=800', description: 'Grand Bazaar, Golestan Palace, and Alborz mountain backdrop.' },
  { id: 'kualalumpur', name: 'Kuala Lumpur', state: 'Malaysia', x: 800, y: 255, image: 'https://images.pexels.com/photos/3787839/pexels-photo-3787839.jpeg?auto=compress&cs=tinysrgb&w=800', description: 'Petronas Towers, rainforest canopy, and multicultural food scene.' },
  { id: 'jakarta', name: 'Jakarta', state: 'Indonesia', x: 810, y: 285, image: 'https://images.pexels.com/photos/280219/pexels-photo-280219.jpeg?auto=compress&cs=tinysrgb&w=800', description: 'Indonesia\'s bustling capital with old town Kota Tua and grand mosques.' },

  // ── Africa ──
  { id: 'cairo', name: 'Cairo', state: 'Egypt', x: 580, y: 215, image: 'https://images.pexels.com/photos/573866/pexels-photo-573866.jpeg?auto=compress&cs=tinysrgb&w=800', description: 'Pyramids of Giza, Nile River, and ancient Egyptian wonders.' },
  { id: 'casablanca', name: 'Casablanca', state: 'Morocco', x: 475, y: 210, image: 'https://images.pexels.com/photos/1534560/pexels-photo-1534560.jpeg?auto=compress&cs=tinysrgb&w=800', description: 'Hassan II Mosque, Art Deco architecture, and Atlantic port.' },
  { id: 'capetown', name: 'Cape Town', state: 'South Africa', x: 545, y: 390, image: 'https://images.pexels.com/photos/3224186/pexels-photo-3224186.jpeg?auto=compress&cs=tinysrgb&w=800', description: 'Table Mountain, Cape of Good Hope, and stunning coastal drives.' },
  { id: 'johannesburg', name: 'Johannesburg', state: 'South Africa', x: 560, y: 380, image: 'https://images.pexels.com/photos/2874168/pexels-photo-2874168.jpeg?auto=compress&cs=tinysrgb&w=800', description: 'Gold rush city with Apartheid Museum and vibrant Soweto.' },
  { id: 'nairobi', name: 'Nairobi', state: 'Kenya', x: 605, y: 310, image: 'https://images.pexels.com/photos/3787839/pexels-photo-3787839.jpeg?auto=compress&cs=tinysrgb&w=800', description: 'Safari capital with Nairobi National Park right at the doorstep.' },
  { id: 'lagos', name: 'Lagos', state: 'Nigeria', x: 510, y: 290, image: 'https://images.pexels.com/photos/2874168/pexels-photo-2874168.jpeg?auto=compress&cs=tinysrgb&w=800', description: 'West Africa\'s mega-city with vibrant music and Nollywood film scene.' },
  { id: 'addisababa', name: 'Addis Ababa', state: 'Ethiopia', x: 595, y: 290, image: 'https://images.pexels.com/photos/2037336/pexels-photo-2037336.jpeg?auto=compress&cs=tinysrgb&w=800', description: 'Highland capital at 2,400m with coffee culture and ancient churches.' },

  // ── Oceania ──
  { id: 'sydney', name: 'Sydney', state: 'Australia', x: 905, y: 340, image: 'https://images.pexels.com/photos/995764/pexels-photo-995764.jpeg?auto=compress&cs=tinysrgb&w=800', description: 'Opera House, Harbour Bridge, and Bondi Beach.' },
  { id: 'melbourne', name: 'Melbourne', state: 'Australia', x: 890, y: 355, image: 'https://images.pexels.com/photos/1878293/pexels-photo-1878293.jpeg?auto=compress&cs=tinysrgb&w=800', description: 'Coffee capital with laneway art, food, and Great Ocean Road nearby.' },
  { id: 'auckland', name: 'Auckland', state: 'New Zealand', x: 960, y: 360, image: 'https://images.pexels.com/photos/532826/pexels-photo-532826.jpeg?auto=compress&cs=tinysrgb&w=800', description: 'City of sails with volcanic cones, harbors, and Pacific views.' },
  { id: 'perth', name: 'Perth', state: 'Australia', x: 835, y: 340, image: 'https://images.pexels.com/photos/995764/pexels-photo-995764.jpeg?auto=compress&cs=tinysrgb&w=800', description: 'Sunniest capital with Indian Ocean beaches and Kings Park.' },
];

export const HIGHWAYS: HighwaySegment[] = [
  // ── North America ──
  { from: 'nyc', to: 'chicago', distance: 790, baseTime: 730, scenicScore: 2, trafficFactor: 1.3, highway: 'I-80 W', image: 'https://images.pexels.com/photos/18348155/pexels-photo-18348155/free-photo-of-traffic-in-city.jpeg?auto=compress&cs=tinysrgb&w=800', description: 'Midwest to East Coast through Pennsylvania turnpike.' },
  { from: 'nyc', to: 'toronto', distance: 490, baseTime: 480, scenicScore: 4, trafficFactor: 1.1, highway: 'I-87 N / ON-401', image: 'https://images.pexels.com/photos/5059237/pexels-photo-5059237.jpeg?auto=compress&cs=tinysrgb&w=800', description: 'Upstate New York through the Adirondacks to Canada.' },
  { from: 'nyc', to: 'miami', distance: 1280, baseTime: 1180, scenicScore: 4, trafficFactor: 1.2, highway: 'I-95 S', image: 'https://images.pexels.com/photos/34573960/pexels-photo-34573960/free-photo-of-scenic-coastal-drive-along-great-ocean-road.jpeg?auto=compress&cs=tinysrgb&w=800', description: 'Classic East Coast run through the Carolinas and Georgia.' },
  { from: 'chicago', to: 'losangeles', distance: 2010, baseTime: 1850, scenicScore: 4, trafficFactor: 0.9, highway: 'I-80 W / I-76 W', image: 'https://images.pexels.com/photos/20512488/pexels-photo-20512488/free-photo-of-highway-through-desert.jpeg?auto=compress&cs=tinysrgb&w=800', description: 'Great Plains crossing through Nebraska and Colorado Rockies.' },
  { from: 'losangeles', to: 'miami', distance: 2750, baseTime: 2500, scenicScore: 5, trafficFactor: 0.8, highway: 'I-10 E', image: 'https://images.pexels.com/photos/34555891/pexels-photo-34555891.jpeg?auto=compress&cs=tinysrgb&w=800', description: 'Southern transcontinental drive through Arizona, Texas, and Gulf Coast.' },
  { from: 'losangeles', to: 'vancouver', distance: 1270, baseTime: 1180, scenicScore: 5, trafficFactor: 1.0, highway: 'I-5 N', image: 'https://images.pexels.com/photos/37194236/pexels-photo-37194236/free-photo-of-scenic-coastal-road-with-ocean-view.jpeg?auto=compress&cs=tinysrgb&w=800', description: 'Pacific Coast through Oregon and Washington — redwoods and ocean cliffs.' },
  { from: 'losangeles', to: 'mexicocity', distance: 1820, baseTime: 1700, scenicScore: 4, trafficFactor: 0.9, highway: 'I-5 S / MX-15 S', image: 'https://images.pexels.com/photos/20512488/pexels-photo-20512488/free-photo-of-highway-through-desert.jpeg?auto=compress&cs=tinysrgb&w=800', description: 'Through Baja California and Sonoran Desert into central Mexico.' },
  { from: 'mexicocity', to: 'miami', distance: 2480, baseTime: 2350, scenicScore: 4, trafficFactor: 0.9, highway: 'MX-180 E / I-95 N', image: 'https://images.pexels.com/photos/34573960/pexels-photo-34573960/free-photo-of-scenic-coastal-drive-along-great-ocean-road.jpeg?auto=compress&cs=tinysrgb&w=800', description: 'Gulf Coast through Veracruz, Yucatán, and up through Texas.' },
  { from: 'toronto', to: 'vancouver', distance: 4300, baseTime: 4100, scenicScore: 5, trafficFactor: 0.7, highway: 'Trans-Canada Hwy', image: 'https://images.pexels.com/photos/5059237/pexels-photo-5059237.jpeg?auto=compress&cs=tinysrgb&w=800', description: 'Epic Trans-Canada Highway through prairies, lakes, and Rocky Mountains.' },
  { from: 'toronto', to: 'chicago', distance: 520, baseTime: 490, scenicScore: 3, trafficFactor: 1.0, highway: 'ON-401 W / I-94 W', image: 'https://images.pexels.com/photos/1096793/pexels-photo-1096793.jpeg?auto=compress&cs=tinysrgb&w=800', description: 'Great Lakes crossing through Ontario and Michigan.' },
  { from: 'toronto', to: 'miami', distance: 1480, baseTime: 1380, scenicScore: 3, trafficFactor: 1.1, highway: 'I-95 S', image: 'https://images.pexels.com/photos/34573960/pexels-photo-34573960/free-photo-of-scenic-coastal-drive-along-great-ocean-road.jpeg?auto=compress&cs=tinysrgb&w=800', description: 'East Coast corridor down through the Appalachians.' },
  { from: 'vancouver', to: 'chicago', distance: 3500, baseTime: 3300, scenicScore: 5, trafficFactor: 0.7, highway: 'I-90 E', image: 'https://images.pexels.com/photos/5059237/pexels-photo-5059237.jpeg?auto=compress&cs=tinysrgb&w=800', description: 'Northern transcontinental through Montana plains and Badlands.' },

  // ── Central & South America ──
  { from: 'mexicocity', to: 'bogota', distance: 3200, baseTime: 3100, scenicScore: 5, trafficFactor: 0.7, highway: 'Pan-American Hwy', image: 'https://images.pexels.com/photos/5059237/pexels-photo-5059237.jpeg?auto=compress&cs=tinysrgb&w=800', description: 'Legendary Pan-American Highway through Central America.' },
  { from: 'bogota', to: 'lima', distance: 2700, baseTime: 2600, scenicScore: 5, trafficFactor: 0.7, highway: 'Pan-American Hwy S', image: 'https://images.pexels.com/photos/34555891/pexels-photo-34555891.jpeg?auto=compress&cs=tinysrgb&w=800', description: 'Andean highway through Ecuador and northern Peru.' },
  { from: 'lima', to: 'buenosaires', distance: 4800, baseTime: 4700, scenicScore: 5, trafficFactor: 0.6, highway: 'Pan-American Hwy S', image: 'https://images.pexels.com/photos/34555891/pexels-photo-34555891.jpeg?auto=compress&cs=tinysrgb&w=800', description: 'Longest Pan-American stretch through Atacama Desert and Pampas.' },
  { from: 'buenosaires', to: 'rio', distance: 2400, baseTime: 2300, scenicScore: 4, trafficFactor: 0.8, highway: 'BR-116 N', image: 'https://images.pexels.com/photos/34573960/pexels-photo-34573960/free-photo-of-scenic-coastal-drive-along-great-ocean-road.jpeg?auto=compress&cs=tinysrgb&w=800', description: 'Through Uruguayan border and southern Brazil.' },
  { from: 'lima', to: 'rio', distance: 4900, baseTime: 4800, scenicScore: 5, trafficFactor: 0.6, highway: 'BR-319 N', image: 'https://images.pexels.com/photos/5059237/pexels-photo-5059237.jpeg?auto=compress&cs=tinysrgb&w=800', description: 'Amazon crossing through Bolivia and central Brazil.' },
  { from: 'bogota', to: 'buenosaires', distance: 6200, baseTime: 6100, scenicScore: 5, trafficFactor: 0.6, highway: 'Pan-American Hwy', image: 'https://images.pexels.com/photos/34555891/pexels-photo-34555891.jpeg?auto=compress&cs=tinysrgb&w=800', description: 'Full Pan-American descent through the Andes.' },
  { from: 'bogota', to: 'rio', distance: 5500, baseTime: 5400, scenicScore: 5, trafficFactor: 0.6, highway: 'BR-174 N', image: 'https://images.pexels.com/photos/5059237/pexels-photo-5059237.jpeg?auto=compress&cs=tinysrgb&w=800', description: 'Through Venezuelan border and Amazon basin into Brazil.' },
  { from: 'lima', to: 'bogota', distance: 2700, baseTime: 2600, scenicScore: 5, trafficFactor: 0.7, highway: 'Pan-American Hwy N', image: 'https://images.pexels.com/photos/34555891/pexels-photo-34555891.jpeg?auto=compress&cs=tinysrgb&w=800', description: 'Andean highway back through Ecuador to Colombia.' },
  { from: 'saopaulo', to: 'rio', distance: 430, baseTime: 400, scenicScore: 3, trafficFactor: 1.2, highway: 'BR-116 N', image: 'https://images.pexels.com/photos/34573960/pexels-photo-34573960/free-photo-of-scenic-coastal-drive-along-great-ocean-road.jpeg?auto=compress&cs=tinysrgb&w=800', description: 'Green coast drive between Brazil\'s two largest cities.' },
  { from: 'saopaulo', to: 'buenosaires', distance: 2600, baseTime: 2500, scenicScore: 4, trafficFactor: 0.8, highway: 'BR-116 S', image: 'https://images.pexels.com/photos/5059237/pexels-photo-5059237.jpeg?auto=compress&cs=tinysrgb&w=800', description: 'Southern Brazil through Paraná pine forests into Argentina.' },

  // ── Europe ──
  { from: 'london', to: 'paris', distance: 460, baseTime: 420, scenicScore: 3, trafficFactor: 1.2, highway: 'A1 / A26', image: 'https://images.pexels.com/photos/18348155/pexels-photo-18348155/free-photo-of-traffic-in-city.jpeg?auto=compress&cs=tinysrgb&w=800', description: 'Channel Tunnel or ferry to Calais, then French autoroute.' },
  { from: 'london', to: 'amsterdam', distance: 540, baseTime: 500, scenicScore: 3, trafficFactor: 1.1, highway: 'A2 / A12', image: 'https://images.pexels.com/photos/10622711/pexels-photo-10622711.jpeg?auto=compress&cs=tinysrgb&w=800', description: 'Through Kent to Dover, ferry to Netherlands.' },
  { from: 'paris', to: 'madrid', distance: 1260, baseTime: 1180, scenicScore: 4, trafficFactor: 0.9, highway: 'A10 S / A-1 S', image: 'https://images.pexels.com/photos/5059237/pexels-photo-5059237.jpeg?auto=compress&cs=tinysrgb&w=800', description: 'Through Loire Valley and Bordeaux vineyards into Spain.' },
  { from: 'paris', to: 'rome', distance: 1420, baseTime: 1340, scenicScore: 5, trafficFactor: 0.9, highway: 'A6 E / A1 S', image: 'https://images.pexels.com/photos/5059237/pexels-photo-5059237.jpeg?auto=compress&cs=tinysrgb&w=800', description: 'Through Burgundy, Alps, and Tuscan countryside.' },
  { from: 'paris', to: 'berlin', distance: 1050, baseTime: 980, scenicScore: 3, trafficFactor: 1.0, highway: 'A4 E', image: 'https://images.pexels.com/photos/1096793/pexels-photo-1096793.jpeg?auto=compress&cs=tinysrgb&w=800', description: 'Through Champagne region and Belgian border into Germany.' },
  { from: 'paris', to: 'barcelona', distance: 1040, baseTime: 970, scenicScore: 5, trafficFactor: 0.9, highway: 'A9 S / AP-7 S', image: 'https://images.pexels.com/photos/37194236/pexels-photo-37194236/free-photo-of-scenic-coastal-road-with-ocean-view.jpeg?auto=compress&cs=tinysrgb&w=800', description: 'Through Provence, lavender fields, and French Riviera.' },
  { from: 'madrid', to: 'barcelona', distance: 620, baseTime: 580, scenicScore: 4, trafficFactor: 0.9, highway: 'AP-2 E', image: 'https://images.pexels.com/photos/5059237/pexels-photo-5059237.jpeg?auto=compress&cs=tinysrgb&w=800', description: 'Across the Meseta plateau through Aragón.' },
  { from: 'madrid', to: 'lisbon', distance: 620, baseTime: 580, scenicScore: 4, trafficFactor: 0.8, highway: 'A-5 W', image: 'https://images.pexels.com/photos/37194236/pexels-photo-37194236/free-photo-of-scenic-coastal-road-with-ocean-view.jpeg?auto=compress&cs=tinysrgb&w=800', description: 'Across the Iberian plains to the Atlantic coast.' },
  { from: 'barcelona', to: 'rome', distance: 1370, baseTime: 1300, scenicScore: 5, trafficFactor: 0.8, highway: 'AP-7 E / A12 S', image: 'https://images.pexels.com/photos/37194236/pexels-photo-37194236/free-photo-of-scenic-coastal-road-with-ocean-view.jpeg?auto=compress&cs=tinysrgb&w=800', description: 'French Riviera to Italian Riviera — Mediterranean coastal drive.' },
  { from: 'berlin', to: 'prague', distance: 350, baseTime: 330, scenicScore: 4, trafficFactor: 0.9, highway: 'A4 S', image: 'https://images.pexels.com/photos/5059237/pexels-photo-5059237.jpeg?auto=compress&cs=tinysrgb&w=800', description: 'Through Saxon Switzerland and Elbe Sandstone Mountains.' },
  { from: 'berlin', to: 'vienna', distance: 660, baseTime: 620, scenicScore: 4, trafficFactor: 0.9, highway: 'A9 S / A4 S', image: 'https://images.pexels.com/photos/5059237/pexels-photo-5059237.jpeg?auto=compress&cs=tinysrgb&w=800', description: 'Through Bavaria and Salzburg — Sound of Music country.' },
  { from: 'prague', to: 'vienna', distance: 330, baseTime: 310, scenicScore: 4, trafficFactor: 0.9, highway: 'D1 S', image: 'https://images.pexels.com/photos/5059237/pexels-photo-5059237.jpeg?auto=compress&cs=tinysrgb&w=800', description: 'Through Moravian countryside and rolling Bohemian hills.' },
  { from: 'vienna', to: 'rome', distance: 1120, baseTime: 1060, scenicScore: 5, trafficFactor: 0.8, highway: 'A23 S / A1 S', image: 'https://images.pexels.com/photos/5059237/pexels-photo-5059237.jpeg?auto=compress&cs=tinysrgb&w=800', description: 'Through Alpine passes, Venice lagoon, and Tuscany.' },
  { from: 'rome', to: 'athens', distance: 1050, baseTime: 990, scenicScore: 5, trafficFactor: 0.8, highway: 'A3 E / Egnatia Odos', image: 'https://images.pexels.com/photos/37194236/pexels-photo-37194236/free-photo-of-scenic-coastal-road-with-ocean-view.jpeg?auto=compress&cs=tinysrgb&w=800', description: 'Adriatic coast ferry to Greece, then through Epirus mountains.' },
  { from: 'athens', to: 'istanbul', distance: 1080, baseTime: 1020, scenicScore: 5, trafficFactor: 0.8, highway: 'E90 E', image: 'https://images.pexels.com/photos/5059237/pexels-photo-5059237.jpeg?auto=compress&cs=tinysrgb&w=800', description: 'Through Thessaloniki and Turkish Thrace.' },
  { from: 'istanbul', to: 'moscow', distance: 1750, baseTime: 1680, scenicScore: 4, trafficFactor: 0.7, highway: 'E105 N', image: 'https://images.pexels.com/photos/5059237/pexels-photo-5059237.jpeg?auto=compress&cs=tinysrgb&w=800', description: 'Through Black Sea coast, Ukraine, and Russian steppes.' },
  { from: 'berlin', to: 'stockholm', distance: 1010, baseTime: 960, scenicScore: 4, trafficFactor: 0.8, highway: 'E4 N', image: 'https://images.pexels.com/photos/5059237/pexels-photo-5059237.jpeg?auto=compress&cs=tinysrgb&w=800', description: 'Ferry to Sweden, then through pine forests and lakes.' },
  { from: 'stockholm', to: 'oslo', distance: 530, baseTime: 500, scenicScore: 4, trafficFactor: 0.8, highway: 'E18 W', image: 'https://images.pexels.com/photos/5059237/pexels-photo-5059237.jpeg?auto=compress&cs=tinysrgb&w=800', description: 'Through Swedish and Norwegian lake districts.' },
  { from: 'oslo', to: 'berlin', distance: 870, baseTime: 830, scenicScore: 4, trafficFactor: 0.8, highway: 'E6 S / E45 S', image: 'https://images.pexels.com/photos/5059237/pexels-photo-5059237.jpeg?auto=compress&cs=tinysrgb&w=800', description: 'Ferry to Denmark, then through Schleswig-Holstein.' },
  { from: 'amsterdam', to: 'berlin', distance: 660, baseTime: 620, scenicScore: 3, trafficFactor: 1.0, highway: 'A2 E / A2 E', image: 'https://images.pexels.com/photos/1096793/pexels-photo-1096793.jpeg?auto=compress&cs=tinysrgb&w=800', description: 'Through Dutch polders and German Ruhr valley.' },
  { from: 'london', to: 'berlin', distance: 1100, baseTime: 1040, scenicScore: 3, trafficFactor: 1.1, highway: 'A3 E / A2 E', image: 'https://images.pexels.com/photos/10622711/pexels-photo-10622711.jpeg?auto=compress&cs=tinysrgb&w=800', description: 'Through Netherlands and northern German plains.' },
  { from: 'amsterdam', to: 'paris', distance: 510, baseTime: 480, scenicScore: 3, trafficFactor: 1.0, highway: 'A2 S / A1 S', image: 'https://images.pexels.com/photos/1096793/pexels-photo-1096793.jpeg?auto=compress&cs=tinysrgb&w=800', description: 'Through Belgian countryside into northern France.' },

  // ── Middle East & Asia ──
  { from: 'istanbul', to: 'tehran', distance: 2050, baseTime: 1980, scenicScore: 5, trafficFactor: 0.7, highway: 'E80 E', image: 'https://images.pexels.com/photos/20512488/pexels-photo-20512488/free-photo-of-highway-through-desert.jpeg?auto=compress&cs=tinysrgb&w=800', description: 'Through Anatolian plateau and Armenian highlands.' },
  { from: 'tehran', to: 'dubai', distance: 1480, baseTime: 1420, scenicScore: 4, trafficFactor: 0.7, highway: 'E05 S', image: 'https://images.pexels.com/photos/34555891/pexels-photo-34555891.jpeg?auto=compress&cs=tinysrgb&w=800', description: 'Through Zagros Mountains and Persian Gulf coast.' },
  { from: 'dubai', to: 'mumbai', distance: 1950, baseTime: 1880, scenicScore: 3, trafficFactor: 0.8, highway: 'E11 E / NH-48 N', image: 'https://images.pexels.com/photos/20512488/pexels-photo-20512488/free-photo-of-highway-through-desert.jpeg?auto=compress&cs=tinysrgb&w=800', description: 'Through Oman ferry to India, then Konkan coast.' },
  { from: 'tehran', to: 'delhi', distance: 3100, baseTime: 3000, scenicScore: 4, trafficFactor: 0.6, highway: 'AH1 E', image: 'https://images.pexels.com/photos/20512488/pexels-photo-20512488/free-photo-of-highway-through-desert.jpeg?auto=compress&cs=tinysrgb&w=800', description: 'Through Afghanistan and Pakistan — ancient Silk Road route.' },
  { from: 'delhi', to: 'mumbai', distance: 1410, baseTime: 1340, scenicScore: 4, trafficFactor: 1.0, highway: 'NH-48 S', image: 'https://images.pexels.com/photos/5059237/pexels-photo-5059237.jpeg?auto=compress&cs=tinysrgb&w=800', description: 'Through Rajasthan desert and Gujarat plains.' },
  { from: 'delhi', to: 'beijing', distance: 4700, baseTime: 4600, scenicScore: 5, trafficFactor: 0.5, highway: 'AH4 E', image: 'https://images.pexels.com/photos/5059237/pexels-photo-5059237.jpeg?auto=compress&cs=tinysrgb&w=800', description: 'Through Himalayas and Tibetan Plateau — epic high-altitude drive.' },
  { from: 'beijing', to: 'shanghai', distance: 1210, baseTime: 1150, scenicScore: 3, trafficFactor: 1.1, highway: 'G2 S', image: 'https://images.pexels.com/photos/10622711/pexels-photo-10622711.jpeg?auto=compress&cs=tinysrgb&w=800', description: 'Through North China Plain and Yangtze River delta.' },
  { from: 'shanghai', to: 'hongkong', distance: 1520, baseTime: 1450, scenicScore: 4, trafficFactor: 1.0, highway: 'G60 S', image: 'https://images.pexels.com/photos/5059237/pexels-photo-5059237.jpeg?auto=compress&cs=tinysrgb&w=800', description: 'Through southeastern China mountains and coastal cities.' },
  { from: 'hongkong', to: 'bangkok', distance: 1850, baseTime: 1780, scenicScore: 5, trafficFactor: 0.7, highway: 'AH3 S', image: 'https://images.pexels.com/photos/5059237/pexels-photo-5059237.jpeg?auto=compress&cs=tinysrgb&w=800', description: 'Through Guangxi karst peaks, Laos, and Thai forests.' },
  { from: 'bangkok', to: 'singapore', distance: 1820, baseTime: 1750, scenicScore: 4, trafficFactor: 0.8, highway: 'AH2 S', image: 'https://images.pexels.com/photos/37194236/pexels-photo-37194236/free-photo-of-scenic-coastal-road-with-ocean-view.jpeg?auto=compress&cs=tinysrgb&w=800', description: 'Through Malaysian rainforest and causeway to Singapore.' },
  { from: 'singapore', to: 'kualalumpur', distance: 360, baseTime: 340, scenicScore: 4, trafficFactor: 1.0, highway: 'E1 N', image: 'https://images.pexels.com/photos/5059237/pexels-photo-5059237.jpeg?auto=compress&cs=tinysrgb&w=800', description: 'North through Johor Bahru and palm oil plantations.' },
  { from: 'kualalumpur', to: 'jakarta', distance: 1180, baseTime: 1120, scenicScore: 4, trafficFactor: 0.8, highway: 'AH2 S', image: 'https://images.pexels.com/photos/5059237/pexels-photo-5059237.jpeg?auto=compress&cs=tinysrgb&w=800', description: 'Through Sumatra rainforests and across Sunda Strait ferry.' },
  { from: 'bangkok', to: 'kualalumpur', distance: 1480, baseTime: 1420, scenicScore: 4, trafficFactor: 0.8, highway: 'AH2 S', image: 'https://images.pexels.com/photos/5059237/pexels-photo-5059237.jpeg?auto=compress&cs=tinysrgb&w=800', description: 'Through Thai-Malay peninsula and rubber plantations.' },
  { from: 'beijing', to: 'seoul', distance: 1480, baseTime: 1420, scenicScore: 4, trafficFactor: 0.8, highway: 'G1 E / ferry', image: 'https://images.pexels.com/photos/5059237/pexels-photo-5059237.jpeg?auto=compress&cs=tinysrgb&w=800', description: 'Through northeastern China and ferry across Yellow Sea.' },
  { from: 'seoul', to: 'tokyo', distance: 1200, baseTime: 1150, scenicScore: 4, trafficFactor: 0.8, highway: 'ferry / expressway', image: 'https://images.pexels.com/photos/5059237/pexels-photo-5059237.jpeg?auto=compress&cs=tinysrgb&w=800', description: 'Ferry across Sea of Japan to Honshu island.' },
  { from: 'tokyo', to: 'osaka', distance: 515, baseTime: 480, scenicScore: 5, trafficFactor: 1.0, highway: 'Tomei Expressway', image: 'https://images.pexels.com/photos/5059237/pexels-photo-5059237.jpeg?auto=compress&cs=tinysrgb&w=800', description: 'Along Pacific coast through Mount Fuji views and Izu Peninsula.' },
  { from: 'shanghai', to: 'seoul', distance: 870, baseTime: 830, scenicScore: 3, trafficFactor: 0.9, highway: 'ferry', image: 'https://images.pexels.com/photos/5059237/pexels-photo-5059237.jpeg?auto=compress&cs=tinysrgb&w=800', description: 'Ferry across East China Sea / Yellow Sea.' },

  // ── Africa ──
  { from: 'cairo', to: 'casablanca', distance: 3600, baseTime: 3500, scenicScore: 5, trafficFactor: 0.6, highway: 'N1 W', image: 'https://images.pexels.com/photos/20512488/pexels-photo-20512488/free-photo-of-highway-through-desert.jpeg?auto=compress&cs=tinysrgb&w=800', description: 'Across North Africa through Libya, Tunisia, and Algeria.' },
  { from: 'cairo', to: 'nairobi', distance: 4900, baseTime: 4800, scenicScore: 5, trafficFactor: 0.5, highway: 'Cairo-Cape Hwy', image: 'https://images.pexels.com/photos/5059237/pexels-photo-5059237.jpeg?auto=compress&cs=tinysrgb&w=800', description: 'Epic African crossing through Sudan, Ethiopia, and Kenya.' },
  { from: 'cairo', to: 'addisababa', distance: 3500, baseTime: 3400, scenicScore: 5, trafficFactor: 0.5, highway: 'N-S Corridor', image: 'https://images.pexels.com/photos/5059237/pexels-photo-5059237.jpeg?auto=compress&cs=tinysrgb&w=800', description: 'Through Sudanese desert and Ethiopian highlands.' },
  { from: 'addisababa', to: 'nairobi', distance: 1450, baseTime: 1400, scenicScore: 5, trafficFactor: 0.6, highway: 'A2 S', image: 'https://images.pexels.com/photos/5059237/pexels-photo-5059237.jpeg?auto=compress&cs=tinysrgb&w=800', description: 'Through Rift Valley lakes and Maasai Mara approaches.' },
  { from: 'nairobi', to: 'capetown', distance: 4100, baseTime: 4000, scenicScore: 5, trafficFactor: 0.5, highway: 'Cairo-Cape Hwy', image: 'https://images.pexels.com/photos/5059237/pexels-photo-5059237.jpeg?auto=compress&cs=tinysrgb&w=800', description: 'Through Tanzania, Zambia, Botswana, and Namibia.' },
  { from: 'nairobi', to: 'johannesburg', distance: 3600, baseTime: 3500, scenicScore: 5, trafficFactor: 0.5, highway: 'A104 S', image: 'https://images.pexels.com/photos/5059237/pexels-photo-5059237.jpeg?auto=compress&cs=tinysrgb&w=800', description: 'Through Tanzania, Malawi, and Zimbabwe.' },
  { from: 'johannesburg', to: 'capetown', distance: 1400, baseTime: 1350, scenicScore: 5, trafficFactor: 0.7, highway: 'N1 W', image: 'https://images.pexels.com/photos/5059237/pexels-photo-5059237.jpeg?auto=compress&cs=tinysrgb&w=800', description: 'Through Karoo semi-desert and Winelands.' },
  { from: 'casablanca', to: 'lagos', distance: 3200, baseTime: 3100, scenicScore: 4, trafficFactor: 0.6, highway: 'Trans-West African Hwy', image: 'https://images.pexels.com/photos/5059237/pexels-photo-5059237.jpeg?auto=compress&cs=tinysrgb&w=800', description: 'Through Mauritania, Senegal, and West African coast.' },
  { from: 'lagos', to: 'addisababa', distance: 4500, baseTime: 4400, scenicScore: 4, trafficFactor: 0.5, highway: 'Trans-African Hwy', image: 'https://images.pexels.com/photos/5059237/pexels-photo-5059237.jpeg?auto=compress&cs=tinysrgb&w=800', description: 'Through Central African Republic and Sudan.' },
  { from: 'casablanca', to: 'madrid', distance: 1150, baseTime: 1100, scenicScore: 4, trafficFactor: 0.8, highway: 'ferry / A-4', image: 'https://images.pexels.com/photos/37194236/pexels-photo-37194236/free-photo-of-scenic-coastal-road-with-ocean-view.jpeg?auto=compress&cs=tinysrgb&w=800', description: 'Ferry across Strait of Gibraltar to Iberian Peninsula.' },

  // ── Oceania ──
  { from: 'sydney', to: 'melbourne', distance: 880, baseTime: 840, scenicScore: 5, trafficFactor: 0.9, highway: 'Hume Hwy / M1', image: 'https://images.pexels.com/photos/37194236/pexels-photo-37194236/free-photo-of-scenic-coastal-road-with-ocean-view.jpeg?auto=compress&cs=tinysrgb&w=800', description: 'Through coastal drive or inland Hume Highway.' },
  { from: 'sydney', to: 'brisbane', distance: 930, baseTime: 890, scenicScore: 5, trafficFactor: 0.9, highway: 'M1 N', image: 'https://images.pexels.com/photos/37194236/pexels-photo-37194236/free-photo-of-scenic-coastal-road-with-ocean-view.jpeg?auto=compress&cs=tinysrgb&w=800', description: 'Pacific Coast through Hunter Valley and Gold Coast.' },
  { from: 'melbourne', to: 'perth', distance: 3420, baseTime: 3300, scenicScore: 5, trafficFactor: 0.5, highway: 'Eyre Hwy', image: 'https://images.pexels.com/photos/20512488/pexels-photo-20512488/free-photo-of-highway-through-desert.jpeg?auto=compress&cs=tinysrgb&w=800', description: 'Across the Nullarbor Plain — one of the world\'s great road trips.' },
  { from: 'auckland', to: 'sydney', distance: 2200, baseTime: 2100, scenicScore: 3, trafficFactor: 0.7, highway: 'ferry / flight', image: 'https://images.pexels.com/photos/37194236/pexels-photo-37194236/free-photo-of-scenic-coastal-road-with-ocean-view.jpeg?auto=compress&cs=tinysrgb&w=800', description: 'Ferry/flight across the Tasman Sea to Australia.' },
  { from: 'perth', to: 'auckland', distance: 5500, baseTime: 5400, scenicScore: 4, trafficFactor: 0.4, highway: 'ferry', image: 'https://images.pexels.com/photos/37194236/pexels-photo-37194236/free-photo-of-scenic-coastal-road-with-ocean-view.jpeg?auto=compress&cs=tinysrgb&w=800', description: 'Long trans-Tasman crossing via ferry to New Zealand.' },
];

export const cityMap: Record<string, CityNode> = Object.fromEntries(CITIES.map(c => [c.id, c]));
